---
settings:
  name: Azure Blob storage
  release_notes_autogen:
    release_notes_repo: console-relnotes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione di Azure Blob Storage
    url: "/index.html"
  - title: Note di rilascio
    url: "/whats-new.html"
  - title: Iniziare
    entries:
    - title: Visualizza i tuoi account di archiviazione BLOB di Azure
      url: "/task-view-azure-blob-storage.html"
  - title: Gestire gli account di archiviazione BLOB di Azure
    entries:
    - title: Aggiungi nuovi account di archiviazione
      url: "/task-add-blob-storage.html"
    - title: Modificare le impostazioni degli account di archiviazione
      url: "/task-change-blob-storage-settings.html"
    - title: Utilizzare i servizi dati NetApp con l'archiviazione BLOB di Azure
      url: "/task-blob-enable-data-services.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere supporto
      url: "/task-support-registration.html"
    - title: Ottieni aiuto
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: Storage Management
  repo: storage-management-family
