---
sidebar: sidebar 
permalink: task-blob-enable-data-services.html 
keywords: blob storage, blob working environment, azure blob storage accounts, azure blob working environment, system 
summary: Dopo aver individuato gli account di archiviazione BLOB di Azure in BlueXP, è possibile utilizzare i servizi dati NetApp per il backup, la suddivisione in livelli e la sincronizzazione dei dati. 
---
= Utilizzare i servizi dati NetApp con l'archiviazione BLOB di Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver individuato gli account di archiviazione BLOB di Azure nella console NetApp , è possibile utilizzare i servizi dati NetApp per il backup, la suddivisione in livelli e la sincronizzazione dei dati.

* Utilizza * NetApp Backup and Recovery* per eseguire il backup dei dati dai tuoi sistemi ONTAP locali e Cloud Volumes ONTAP nell'archiviazione BLOB di Azure.
+
Per iniziare, vai alla pagina Sistemi.  Trascina e rilascia un sistema ONTAP locale o Cloud Volumes ONTAP sul tuo sistema Azure Blob Storage.

+
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Scopri di più sul backup dei dati ONTAP nell'archiviazione BLOB di Azure"^] .

* Utilizzare * NetApp Cloud Tiering* per suddividere in livelli i dati inattivi dai cluster ONTAP locali all'archiviazione BLOB di Azure.
+
Per iniziare, vai alla pagina Sistemi.  Trascina e rilascia un sistema ONTAP locale sul tuo sistema Azure Blob Storage.

+
https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-azure.html["Scopri di più sulla suddivisione in livelli dei dati ONTAP nell'archiviazione BLOB di Azure"^] .

* Utilizzare * NetApp Copy and Sync* per sincronizzare i dati da o verso gli account di archiviazione BLOB di Azure.
+
Per iniziare, vai alla pagina Sistemi.  Trascinare e rilasciare il sistema sorgente sul sistema di destinazione.  Il sistema Azure Blob Storage può essere sia l'origine che la destinazione.

+
È anche possibile selezionare il sistema di archiviazione BLOB di Azure, quindi *Copia e sincronizza* dal pannello Servizi per sincronizzare i dati da o verso gli account di archiviazione BLOB di Azure.

+
https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["Scopri di più su Copia e sincronizzazione"^] .


