---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, limitations, known issues, enhancements, fixes' 
summary: Scopri le novità di Azure Blob Storage nella NetApp Console. 
---
= Novità di Azure Blob Storage nella NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità di Azure Blob Storage nella NetApp Console.



== 06 ottobre 2025



=== BlueXP è ora NetApp Console

BlueXP è stato rinominato e riprogettato per riflettere meglio il suo ruolo nella gestione dell'infrastruttura dati.

NetApp Console offre una gestione centralizzata dei servizi di storage e dati in ambienti on-premise e cloud di livello aziendale, offrendo informazioni in tempo reale, flussi di lavoro più rapidi e amministrazione semplificata.

Per i dettagli su cosa è cambiato, vedere il https://docs.netapp.com/us-en/console-relnotes/index.html["Note sulla versione NetApp Console"] .



== 05 giugno 2023



=== Possibilità di aggiungere nuovi account di archiviazione da BlueXP

È da un po' che hai la possibilità di visualizzare Azure Blob Storage su BlueXP Canvas.  Ora puoi aggiungere nuovi account di archiviazione e modificare le proprietà degli account di archiviazione esistenti direttamente da BlueXP. link:https://docs.netapp.com/us-en/storage-management-blob-storage/["Scopri come aggiungere nuovi account di archiviazione BLOB di Azure"^] .
